### ISSUE TITLE
Override phpcs args

### ISSUE THREAD

**Issue by gabrielbidula** [creativenull/diagnosticls-configs-nvim#14]
Hi,

Is it possible to override the args settings for phpcs?

from 
`args = {'--standard=PSR2', '--report=emacs', '-s', '-'},`

to
`args = {'--standard=PSR12'}`

**Comment by creativenull** [comment]
Hey, It's part of my [TODO](https://github.com/creativenull/diagnosticls-configs-nvim#todo) which I plan to tackle today or tomorrow given my free time 🙂

ATM you should be able to override the setting with a `phpcs.xml` file in your project. Let me know if that works for you. I could do a quick patch to remove `--standard` is that take priority vs the `phpcs.xml` file

**Comment by gabrielbidula** [comment]
Cool, I added a phpcs.xml file with rules regarding PSR12 but I cannot see them on the respective files inside nvim. There is no diagnostic showing up.

This is my setup

```require 'diagnosticls-configs'.init {
  on_attach = on_attach
}

local phpcs = require 'diagnosticls-configs.linters.phpcs'
require 'diagnosticls-configs'.setup {
  ['php'] = {
    linter = phpcs,
  },
}
EOF```

I might be missing something.

**Comment by creativenull** [comment]
How does your phpcs.xml file look?

May want to check what the output is in the terminal as well with:

```
phpcs --report=emacs -s <file>
```

Either way I'll look into implementing a way to pass custom arguments to the linters/formatters

**Comment by creativenull** [comment]
In addition to that, it's possible to extend the config as well, not sure why it didn't come up on my mind until now. But you could do something like the following to override the `args` key:

```lua
local phpcs = require 'diagnosticls-configs.linters.phpcs'

phpcs = vim.tbl_extend('force', phpcs, {
  args = {'--standard=PSR12', '--report=emacs', '-s', '-'},
})

require 'diagnosticls-configs'.setup {
  ['php'] = {
    linter = phpcs,
  },
}
```

**Comment by gabrielbidula** [comment]
Nice, that would work!

Although I cannot see the diagnostic inside the file.

Running on terminal,
<img width="1672" alt="Screenshot 2021-08-23 at 08 32 00" src="https://user-images.githubusercontent.com/1028654/130401231-14376538-bf9e-4570-a45a-62811166f920.png">

Then inside nvim I would expect to be like this,
<img width="963" alt="Screenshot 2021-08-23 at 08 33 32" src="https://user-images.githubusercontent.com/1028654/130401389-ec8d35b9-0b51-4256-8d55-fab16e56fd45.png">

Am I right?

**Comment by creativenull** [comment]
Are you sure it's not working? From the screenshot you provided, looks like you are calling phpcs from `~/.composer` directory, is that already in your `$PATH`? Because it should be, else it will look for `phpcs` in the `vendor/bin/phpcs` located in your project directory.

---

I've tried it in my Laravel project and seems like it works. (The classic "works on my machine")

Here is my phpcs.xml

```xml
<?xml version="1.0"?>
<ruleset name="Project Standard">
    <rule ref="PSR12" />

    <file>app</file>
    <file>bootstrap</file>
    <file>config</file>
    <file>database</file>
    <file>resources</file>
    <file>routes</file>
    <file>tests</file>

    <exclude-pattern>bootstrap/cache/*</exclude-pattern>
    <exclude-pattern>bootstrap/autoload.php</exclude-pattern>
    <exclude-pattern>*/migrations/*</exclude-pattern>
    <exclude-pattern>*/seeds/*</exclude-pattern>
    <exclude-pattern>*.blade.php</exclude-pattern>
    <exclude-pattern>*.js</exclude-pattern>

    <arg value="p"/>
</ruleset>
```

And I have attached without the PSR12 standard so it will be picked up by the phpcs.xml file:

```lua
-- init.lua
local phpcs = require('diagnosticls-configs.linters.phpcs')
phpcs = vim.tbl_extend('force', phpcs, {
  args = {'--report=emacs', '-s', '-'}
})
```

Here is the screenshot with the error:

![image](https://user-images.githubusercontent.com/3767728/130468097-a05dd32e-e9cb-4568-a221-bfe6e4be695d.png)

**Comment by gabrielbidula** [comment]
Hi, you were right I think I didn't have it on my path for some reason. Anyway, it seems to be working now.
You can close this topic, good job!
