### ISSUE TITLE
luacheck only lints on write

### ISSUE THREAD

**Issue by mrjones2014** [creativenull/diagnosticls-configs-nvim#20]
Copy/pasted the `luacheck` config, I have luacheck installed, and it gives no diagnostics. There's no errors in `~/.cache/nvim/lsp.log`

```
> luacheck --version
Luacheck: 0.23.0
Lua: PUC-Rio Lua 5.4
Argparse: 0.7.1
LuaFileSystem: 1.8.0
LuaLanes: Not found
```

**Comment by creativenull** [comment]
Hey, do you have a `.luacheckrc` in the root project? It looks for that according to the root patterns. You could change it to maybe `.git` to let it run on any git directory by extending it out:

```lua
local luacheck = require 'diagnosticls-configs.linters.luacheck'

luacheck = vim.tbl_extend('force', luacheck, {
  rootPatterns = {'.git'}
})
```

**Comment by mrjones2014** [comment]
Whoops, I feel dumb 🤦 

I will test again when I’m back at my dev machine. Will reopen if issue persists.

thanks!

**Comment by mrjones2014** [comment]
So I added a `.luacheckrc` but it's not attaching to the buffer. I tried adding `init.lua` and `stylua.toml` (both of which exist in my root) to `rootPatterns` and still no luck.

![image](https://user-images.githubusercontent.com/8648891/131408358-e24ffecc-7a04-4e27-bcbb-749c6f359ac4.png)


![image](https://user-images.githubusercontent.com/8648891/131408394-b5434a13-2fbb-4259-b521-3144c1472bb8.png)

**Comment by mrjones2014** [comment]
Actually, I did manage to get it working. however it only lints on save. is there a way to trigger lint on entering normal mode?

**Comment by mrjones2014** [comment]
(updated the title to reflect the new issue)

**Comment by creativenull** [comment]
I see, you're right it only lints on save. And that's because I have it set to read from the file instead of from stdin.

Looks like luacheck does have a way lint via stdin, so i can patch that in to use that instead :)

**Comment by creativenull** [comment]
Updated in 806f6d1 can you check and see if you still see the issue?

**Comment by mrjones2014** [comment]
Yup that fixed it! Thanks!
