### ISSUE TITLE
Linting files in directories without '.git'

### ISSUE THREAD

**Issue by dirtyhabits97** [creativenull/diagnosticls-configs-nvim#22]
## How to reproduce
1. Create a `*.sh` file in a folder without `.git`
2. Open the file with neovim

## What happens?
The plugin doesn't get attached:

<img width="691" alt="Screen Shot 2021-09-18 at 15 54 24" src="https://user-images.githubusercontent.com/25568998/133908275-0bc2495b-508c-4504-a4ac-78cdb2a1500f.png">

I expected the plugin to be attached with shellcheck as the linter. 
When I attach it inside a git repo it works:

<img width="696" alt="Screen Shot 2021-09-18 at 15 56 53" src="https://user-images.githubusercontent.com/25568998/133908334-9624b71e-c1a3-4ab9-88d9-c5fee9832875.png">

*** 

## My config
```
local dlsconfig = require 'diagnosticls-configs'
local shellcheck = require 'diagnosticls-configs.linters.shellcheck'
local swiftlint = require 'diagnosticls-configs.linters.swiftlint'

swiftlint = vim.tbl_extend('force', swiftlint, {
  rootPatterns = {'Package.swift', '.git'}
})

dlsconfig.setup {
  ['sh'] = {
    linter = shellcheck
  },
  ['swift'] = {
    linter = swiftlint
  },
}
```

The same thing happens with `swiftlint`. Notice how in my config I specify `{'Package.swift', '.git'}` as the root pattern.
In my folder's root I have a `Package.swift` file, but the plugin doesn't attach:

<img width="681" alt="Screen Shot 2021-09-18 at 16 00 20" src="https://user-images.githubusercontent.com/25568998/133908424-73bcf2b7-773c-4620-b5a4-febd98a2f194.png">

***

I noticed that this is the only place where `root_dir` is referenced.
https://github.com/creativenull/diagnosticls-configs-nvim/blob/cd94a1ed9e133b6894a186c315084e5122952df4/lua/diagnosticls-configs/init.lua#L5

To make `SwiftLint` work, I changed it to:
```
root_dir = require'lspconfig'.util.root_pattern('Package.swift', '.git'), 
```

To make `shellcheck` work, I changed it to:
```
root_dir = function(fname)
  return util.root_pattern '.git'(fname) or util.path.dirname(fname)
end,
``

**Comment by creativenull** [comment]
Hey, yes this is the intended behavior I had when initially adding `root_dir` to only run diagnostic LS when present in a git repo. My assumption was on language servers running in projects and not single files.

Unfortunately, lspconfig will require you to add some root pattern and Diagnostic LS also requires another set of root patterns (like you've done with swiflint). I'm still open to suggestions, but this will be more dependent on `lspconfig` than this repo.

You can, however, override the `root_dir` in the `init()` function before calling `setup()` (taking from your example):

```lua
local util = require('lspconfig').util
local dlsconfig = require 'diagnosticls-configs'
local shellcheck = require 'diagnosticls-configs.linters.shellcheck'
local swiftlint = require 'diagnosticls-configs.linters.swiftlint'

swiftlint = vim.tbl_extend('force', swiftlint, {
  rootPatterns = {'Package.swift', '.git'}
})

-- Use root directory here just for diagnosticls for shell files
dlsconfig.init {
  root_dir = function()
    return util.root_pattern '.git'(fname) or util.path.dirname(fname)
  end,
}

dlsconfig.setup {
  ['sh'] = {
    linter = shellcheck
  },
  ['swift'] = {
    linter = swiftlint
  },
}
```

**Comment by dirtyhabits97** [comment]
Overriding `root_dir` during initialization did the trick.

Thanks 👍
