### ISSUE TITLE
Did you support mypy?

### ISSUE THREAD

**Issue by nyngwang** [creativenull/diagnosticls-configs-nvim#28]
As title.

**Comment by creativenull** [comment]
Doesn't look like I have a config for that, I can take a look at it later today and add it if I can.

Else others are free to make a PR on it if interested!

**Comment by creativenull** [comment]
Added in [eed632a](https://github.com/creativenull/diagnosticls-configs-nvim/commit/eed632a079064bdf415f1f9e128998da3b61bff0)

Try it out and let me know if there is anything missing.

**Comment by creativenull** [comment]
I'll keep this open for a couple days, if there are no issues then I will close it.

**Comment by LukasDoesDev** [comment]
Could this be added to `supported-linters-and-formatters.md`?

**Comment by creativenull** [comment]
[Done](https://github.com/creativenull/diagnosticls-configs-nvim/blob/main/supported-linters-and-formatters.md#linters-6)
